# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [2]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression as LinReg
from sklearn import metrics
import numpy as np
from sklearn.linear_model import Ridge, Lasso
from sklearn.linear_model import SGDRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR

# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function.

In [31]:
from sklearn.datasets import load_diabetes 
diabetes = load_diabetes()

Let's explore this variable by looking at the different attributes. Do this by looking at the `keys()` of this variable.

In [32]:
diabetes.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [13]:
help(load_diabetes)

Help on function load_diabetes in module sklearn.datasets._base:

load_diabetes(*, return_X_y=False, as_frame=False, scaled=True)
    Load and return the diabetes dataset (regression).
    
    ==============   ==================
    Samples total    442
    Dimensionality   10
    Features         real, -.2 < x < .2
    Targets          integer 25 - 346
    ==============   ==================
    
    .. note::
       The meaning of each feature (i.e. `feature_names`) might be unclear
       (especially for `ltg`) as the documentation of the original dataset is
       not explicit. We provide information that seems correct in regard with
       the scientific literature in this field of research.
    
    Read more in the :ref:`User Guide <diabetes_dataset>`.
    
    Parameters
    ----------
    return_X_y : bool, default=False
        If True, returns ``(data, target)`` instead of a Bunch object.
        See below for more information about the `data` and `target` object.
    
    

The next step is to read the description of the dataset. Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable

In [15]:
print(diabetes.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

Note: Each of these 1

What are the variables in this dataset according to the description? List them in the markdown cell below

diabetes = pd.DataFrame(load_diabetes().data, columns = load_diabetes().feature_names)



Now explore the data. Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). In the cell below find the shape of the numpy array contained in the data portion of the diabetes variable.

In [17]:
diabetes = pd.DataFrame(load_diabetes().data, columns = load_diabetes().feature_names)

In [18]:
diabetes.keys()

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')

In [20]:
diabetes.shape

(442, 10)

# Challenge 2 - Perform Supervised Learning on the Dataset

#### The data has already been split to predictor and response variables. The response variable is in the `target` portion of the variable. 

Given this information, let's apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset. In the cell below, import the linear regression class from sklearn. 

In [24]:
from sklearn.linear_model import LinearRegression as LinReg

In [26]:
lr = LinReg()

Initialize the model in the variable `diabetes_model`

In [29]:
diabetes_model = LinReg()

In the cell below, fit the model and print the intercept and coefficients of the model. 

In [33]:
diabetes_model.fit(diabetes.data, diabetes.target)

LinearRegression()

In [34]:
diabetes_model.coef_

array([ -10.0098663 , -239.81564367,  519.84592005,  324.3846455 ,
       -792.17563855,  476.73902101,  101.04326794,  177.06323767,
        751.27369956,   67.62669218])

In [36]:
diabetes_model.intercept_

152.13348416289597

# Bonus Challenge 1 - Conduct a Hypothesis Test on the Model

Once we have generated a linear model, we can test each coefficient using a t-test to see whether the confidence interval for the variable contains zero. We can also perform an overall F test to check whether at least one coefficient is significantly different from zero. 

Refer to the resource in this [link](https://onlinecourses.science.psu.edu/stat501/node/297/) for more details and perform the t-tests for the model above. Additionally, interpret the results and list coefficients are significantly different from zero.


Hint: use the statsmodels package.

Your result should look similar to this:

![ols](../ols-results.png)

In [182]:
# Your code here:



# Challenge 2 - Peform Supervised Learning on a Pandas Dataframe

Now that we have looked at data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [73]:
auto = pd.read_csv('../auto-mpg.csv')

Look at the first 5 rows using the `head()` function:

In [74]:
auto.head()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"  
1          70          \t"buick skylark 320"  
2          70         \t"plymouth satellite"  
3          70              \t"amc rebel sst"  
4          70                \t"ford torino"

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [75]:
auto.dtypes

mpg             float64
cylinders         int64
displacement    float64
horse_power     float64
weight            int64
acceleration    float64
model_year        int64
car_name         object
dtype: object

What is the newest model year and the oldest model year?

In [76]:
max(auto.model_year)

82

In [77]:
min(auto.model_year)

70

Check the dataset for missing values and remove all rows containing at least one missing value.

In [78]:
auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horse_power     6
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

In [79]:
auto.dropna(inplace= True)

In [80]:
auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horse_power     0
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [81]:
auto.cylinders.value_counts()

4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

In [82]:
auto = auto.drop(columns="car_name")

In [96]:
lr = LinReg()

In [107]:
X = auto.drop("mpg", axis = 1)
y = auto.mpg

Now we will the dataset that we processed and peform linear regression on this data to predict the mpg for each vehicle. Initialize the model in the cell below.

In [98]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

Next, fit the model in the cell below.

In [99]:
regression = lr.fit(X_train, y_train)

# Challenge 3 - Evaluate the Model

the r squared score of a model tells us how much variation is explained by the model. In a typical dataset, most observations differ from the mean. When we create a model, we are trying to generate an equation that will tell us by how much each observation will differ from the mean. Obviously, the vast majority of models are not perfect. They can only predict some of the variation from the mean but not all of it. We attribute the rest of the difference between the actual value and the mean to random error. We would like random error to explain the as little as possible of the variation. This is why the r squared score is an important metric.

In the next cell, compute the r squared score of the model. Do this by first computing the predicted values and assign them to `y_pred`.

In [87]:
lr.coef_

array([-0.40015085,  0.00481356, -0.00713666, -0.00614095,  0.01358222,
        0.72885095])

In [88]:
lr.intercept_

-11.822665175562836

In [100]:
y_pred = regression.predict(X_test)

In [101]:
y_pred

array([34.47076243, 30.80914401, 20.21717392, 25.17329077, 33.34304223,
        9.8566988 , 33.39762095, 33.2750958 , 27.82306355, 24.70040104,
       13.70485887, 14.0434236 , 15.42250045, 17.55916141, 28.26144864,
       31.84307783, 25.43835727, 30.53386672, 27.6165472 , 16.01229145,
       17.70651444, 27.1239309 , 14.94127666, 23.34390325, 32.07849148,
       13.88329485, 30.18922205, 19.80464418, 35.16700116, 15.2540299 ,
       33.58067606, 21.01854511, 25.9372521 , 20.96749526, 29.82684554,
       30.22836737, 30.61040887, 31.02976251, 28.59382818, 30.39278755,
       26.8075034 , 19.56311128, 14.28576114, 16.4671469 , 12.72049546,
       33.97606575, 18.85096342, 22.16421643, 10.92998683, 29.46569768,
       12.61060398, 11.92445388, 24.71117207, 22.06623296, 21.6198054 ,
       32.28322177, 21.84134168, 24.9771347 , 29.25336176, 11.24161987,
       18.62740243, 17.65950163, 34.38637897, 31.37335785,  6.4986012 ,
       19.44953551,  8.29174248, 10.19946531, 28.6224918 , 14.96

In [103]:
print(f"r2: {metrics.r2_score(y_test, y_pred)}")

r2: 0.8527204791508918


#### Our next step is to evaluate the model using the test data. We would like to ensure that our model is not overfitting the data. This means that our model will not be able to generalize well outside of the training data.

In the cell below, use the model to generate the predicted values for the training data and assign them to `y_test_pred`. Compute the r squared score for the test data by comparing the oberserved `y_test` data and the predicted `y_test_pred`.

In [108]:
y_pred1 = regression.predict(X_train)
y_pred1

array([31.37600832, 29.61716887, 29.88199432, 31.06065421, 22.48430585,
       24.87466325, 31.04563333, 32.56532936, 28.69706645, 32.6936024 ,
       33.19994244, 13.09381269, 10.35195921, 21.89188943, 23.0758626 ,
       26.54199558, 21.36116886, 26.928819  , 28.95563417,  7.78961928,
       24.10881231, 21.93193177, 25.68372617, 16.05859949, 28.3263428 ,
       19.00167763, 26.35536941, 28.70549521, 21.33111515, 23.35737235,
       17.11948021, 24.13133667, 12.42349536, 33.68306296, 17.75594632,
       11.16733041, 25.75414022, 21.74951956, 23.37542224, 26.45995211,
       19.83278063, 28.70666283, 21.68484623, 25.77680042, 15.52673778,
       21.87236479, 31.14201631, 26.06408097, 20.89751492, 23.64708713,
       10.30689423, 31.04905226, 19.61489153, 23.90882708, 33.78960905,
       17.59939718, 10.12611128, 30.05495584, 30.63908846, 20.29072378,
       11.32561834, 22.76253792, 26.91328362, 15.3321717 , 28.41687452,
       32.24973489, 25.55542731, 27.46030377, 29.68730504, 17.87

In [109]:

print(f"r2: {metrics.r2_score(y_train, y_pred1)}")

r2: 0.7958628049539552


# Challenge 4 - Improve the Model Fit

While the most common way to improve the fit of a model is by using regularization, there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [61]:
X_train09, X_test09, y_train09, y_test09 = train_test_split(X, y, test_size=0.1)


Initialize a new model. Name this model `auto_model09`. Fit the model to the new sample data.

In [62]:
auto_model09 = lr.fit(X_train09, y_train09)

Compute the predicted values and r squared score for our new model and new sample data.

In [63]:
y_pred09 = lr.predict(X_test09)

In [64]:
y_pred09

array([28.8302991 , 27.82425049, 27.79551516, 24.36694557, 12.97930288,
       25.1515155 , 10.52975015, 24.75224369, 25.31553635, 24.80413927,
       31.18013337, 20.29434705, 24.07875156, 28.76006871, 13.84177582,
       21.21117846, 15.1009655 , 30.87090611, 17.92380532, 30.22011013,
       13.69556445, 33.55353642, 16.55648308, 16.04699746, 16.63248594,
       22.60854852, 27.77657078, 25.74493685, 20.75010897, 30.18958381,
       12.77802953, 26.81734886, 15.21997016, 23.7835797 , 16.9427089 ,
       24.73213402, 20.85560015, 30.74788337, 32.03507996, 20.64742881])

Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [65]:
print(f"MAE, error: {metrics.mean_absolute_error(y_test09, y_pred09)}")
print(f"MSE, error: {metrics.mean_squared_error(y_test09, y_pred09)}")
print(f"RMSE, error: {np.sqrt(metrics.mean_squared_error(y_test09, y_pred09))}")
print(f"r2: {metrics.r2_score(y_test09, y_pred09)}")


MAE, error: 1.8925752163813119
MSE, error: 5.9046747056561735
RMSE, error: 2.4299536426969492
r2: 0.8551692238946865


# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [200]:
# Your code here:



Fit the model and print the ranking

In [201]:
# Your code here:



Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_train_reduced`, `y_test_reduced`. Use an 80% split.

In [202]:
# Your code here:



Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [203]:
# Your code here: 

